#include "res/code/audio/ambiance.h"
#include "res/code/audio/banana.h"
#include "res/code/audio/heartbeat.h"
#include "res/code/audio/manga.h"
#include "res/code/audio/walk.h"
#include "res/code/audio/zegotinha.h"

#include "res/code/bricks.h"
#include "res/code/carpet.h"
#include "res/code/controls.h"
#include "res/code/lula.h"
#include "res/code/map.h"
#include "res/code/path.h"
#include "res/code/player.h"